### ISSUE TITLE
无法找到名为lib.monotonic_align.monotonic_align.core的模块

### ISSUE THREAD

**Issue by input111** [open-moss/moss-tts-service#2]
无法找到名为lib.monotonic_align.monotonic_align.core的模块
`D:\.AI\moss-tts-service-master>D:\.AI\moss-tts-service-master\server.py
Traceback (most recent call last):
  File "D:\.AI\moss-tts-service-master\server.py", line 8, in <module>
    import lib.monotonic_align.monotonic_align.core
  File "D:\.AI\moss-tts-service-master\lib\monotonic_align\__init__.py", line 3, in <module>
    from .monotonic_align.core import maximum_path_c
ModuleNotFoundError: No module named 'lib.monotonic_align.monotonic_align.core'`

**Comment by Vinlic** [comment]
尝试重新构建一下monotonic_align
cd monotonic_align
mkdir monotonic_align
python setup.py build_ext --inplace
cd ..

**Comment by SupritYoung** [comment]
setup.py 这个文件也没有
